services:
  db:
    image: postgres:16-alpine
    container_name: smartticket-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ticketuser
      POSTGRES_PASSWORD: ticketpass
      POSTGRES_DB: smartticket
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticketuser -d smartticket"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  api:
    build: .
    container_name: smartticket-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
  
  worker:
    build: .
    container_name: smartticket-worker
    restart: unless-stopped
    command: ["python","worker.py"]
    env_file:
      - .env
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
volumes:
  pgdata:
